WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 44, in autodetect
    from . import file_cache
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:[{'kind': 'calendar#event', 'etag': '"3235411324598000"', 'id': '1k6uam1hpv4ipbsd8h9kpculfs', 'status': 'confirmed', 'htmlLink': 'https://www.google.com/calendar/event?eid=MWs2dWFtMWhwdjRpcGJzZDhoOWtwY3VsZnMgY182YzZ1ZTIwY3VnZmlzdjdyaDc5c2dlNzVnZ0Bn', 'created': '2021-04-06T09:45:22.000Z', 'updated': '2021-04-06T11:32:32.383Z', 'summary': 'Send 7807445246', 'description': 'Hello Send a message.', 'creator': {'email': 'randy@fightonmentality.com'}, 'organizer': {'email': 'c_6c6ue20cugfisv7rh79sge75gg@group.calendar.google.com', 'displayName': 'FOM - Paid Reminders', 'self': True}, 'start': {'dateTime': '2021-04-06T06:00:00-07:00'}, 'end': {'dateTime': '2021-04-06T07:00:00-07:00'}, 'iCalUID': '1k6uam1hpv4ipbsd8h9kpculfs@google.com', 'sequence': 0, 'reminders': {'useDefault': False}, 'eventType': 'default'}]
INFO:werkzeug:127.0.0.1 - - [06/Apr/2021 17:04:38] "[37mGET /dashboard HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2021 17:04:39] "[37mGET /static/sms4_43518.ico HTTP/1.1[0m" 200 -
INFO:werkzeug: * Detected change in 'C:\\Users\\USER\\Desktop\\VCODE\\Peachie GREMINDER\\MainCode\\DEPLOY\\project\\main.py', reloading
